// 31 sinh viên — dữ liệu khảo sát thô (đã ẩn danh)
// Cấu trúc: nam_hoc, truong, gioi_tinh, ton_giao, B1..B10

export type Response = {
  year: "Năm 1" | "Năm 2" | "Năm 3" | "Năm 4"
  school: string
  gender: "Nam" | "Nữ"
  religion: string
  B1_pressure: number // 1–5: áp lực kỳ vọng
  B4_success: string
  B2_emptiness: number // 1–5: trống rỗng
  B3_needBigger: number // 1–5: cần điều lớn hơn thành tích
  B5_priority: number // 1–10: ưu tiên tìm hiểu niềm tin
  B6_view: string // góc nhìn về Đức Chúa Trời
  B7_beliefPct: number // 0–10 → % tin có Chúa
  B8_barrier: string // lý do khó tin
  B9_openness: number // 1–5: mức sẵn sàng lắng nghe
  B10_questions: string[] // các câu hỏi chưa thỏa mãn
}

export const responses: Response[] = [
  { year: "Năm 1", school: "IUH", gender: "Nam", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 3, B3_needBigger: 3, B5_priority: 5, B6_view: "Tôi không biết và không chắc (bất khả tri)", B7_beliefPct: 5, B8_barrier: "Tôn giáo bị lợi dụng để kiếm tiền / quyền lực", B9_openness: 3, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Có bình an nội tâm — biết mình là ai và mình thuộc về đâu", B2_emptiness: 4, B3_needBigger: 3, B5_priority: 3, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 2, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 2, B10_questions: ["Tại sao có quá nhiều tôn giáo — cái nào đúng?", "Nếu Chúa thật, tại sao Ngài im lặng trước đau khổ của tôi?", "Tại sao người theo đạo vẫn sống giả hình, phán xét người khác?", "Tôi là ai và mình đang sống vì điều gì?"] },
  { year: "Năm 3", school: "IUH", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Có bình an nội tâm — biết mình là ai và mình thuộc về đâu", B2_emptiness: 5, B3_needBigger: 4, B5_priority: 6, B6_view: "Tôi tin là có Đức Chúa Trời", B7_beliefPct: 10, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 5, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?", "Sau khi chết, chúng ta sẽ đi về đâu?", "Tại sao có quá nhiều tôn giáo — cái nào đúng?", "Vũ trụ hình thành từ đâu — khoa học hay Đức Chúa Trời?"] },
  { year: "Năm 3", school: "IUH", gender: "Nam", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 3, B3_needBigger: 3, B5_priority: 9, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 1, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 2, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?"] },
  { year: "Năm 4", school: "IUH", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 5, B3_needBigger: 3, B5_priority: 8, B6_view: "Tôi không biết và không chắc (bất khả tri)", B7_beliefPct: 5, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 3, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?", "Có một chân lý tuyệt đối không, hay mọi thứ đều tương đối?", "Tại sao có quá nhiều tôn giáo — cái nào đúng?", "Tôi là ai và mình đang sống vì điều gì?"] },
  { year: "Năm 2", school: "HaUI", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 3, B4_success: "Được công nhận, có danh tiếng trong lĩnh vực mình làm", B2_emptiness: 2, B3_needBigger: 2, B5_priority: 6, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 1, B8_barrier: "Khoa học đã giải thích được hầu hết mọi thứ", B9_openness: 1, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?", "Tôi là ai và mình đang sống vì điều gì?", "Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 3", school: "HUIT", gender: "Nam", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 4, B3_needBigger: 4, B5_priority: 4, B6_view: "Có thể có một Đấng Tạo Hóa, nhưng tôi chưa rõ", B7_beliefPct: 6, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 3, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?", "Sau khi chết, chúng ta sẽ đi về đâu?", "Khoa học và đức tin có thể cùng tồn tại không?", "Tôi sống tốt đã đủ chưa, cần gì đến Chúa hay đức tin?"] },
  { year: "Năm 3", school: "UTE", gender: "Nam", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 5, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 5, B3_needBigger: 5, B5_priority: 7, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 5, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 3, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 1", school: "UFM", gender: "Nam", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 4, B3_needBigger: 4, B5_priority: 8, B6_view: "Tôi đang tìm hiểu và cởi mở", B7_beliefPct: 8, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 4, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?", "Nếu Chúa thật, tại sao Ngài im lặng trước đau khổ của tôi?", "Vũ trụ hình thành từ đâu — khoa học hay Đức Chúa Trời?"] },
  { year: "Năm 1", school: "HCMUT", gender: "Nữ", religion: "Không theo tôn giáo nào", B1_pressure: 3, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 3, B3_needBigger: 2, B5_priority: 3, B6_view: "Tôi khá chắc là không có Chúa / thần linh", B7_beliefPct: 1, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 3, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nữ", religion: "Không theo tôn giáo nào", B1_pressure: 3, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 3, B3_needBigger: 3, B5_priority: 5, B6_view: "Tôi không biết và không chắc (bất khả tri)", B7_beliefPct: 3, B8_barrier: "Không thể thấy, nghe, hay cảm nhận Chúa trực tiếp", B9_openness: 2, B10_questions: ["Khoa học và đức tin có thể cùng tồn tại không?"] },
  { year: "Năm 1", school: "HUIT", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 5, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 5, B3_needBigger: 5, B5_priority: 7, B6_view: "Tôi đang tìm hiểu và cởi mở", B7_beliefPct: 8, B8_barrier: "Không thể thấy, nghe, hay cảm nhận Chúa trực tiếp", B9_openness: 3, B10_questions: ["Khoa học và đức tin có thể cùng tồn tại không?", "Tại sao có quá nhiều tôn giáo — cái nào đúng?", "Tại sao người theo đạo vẫn sống giả hình, phán xét người khác?", "Vũ trụ hình thành từ đâu — khoa học hay Đức Chúa Trời?"] },
  { year: "Năm 1", school: "IU", gender: "Nữ", religion: "Không theo tôn giáo nào", B1_pressure: 2, B4_success: "Có bình an nội tâm — biết mình là ai và mình thuộc về đâu", B2_emptiness: 4, B3_needBigger: 3, B5_priority: 4, B6_view: "Tôi đang tìm hiểu và cởi mở", B7_beliefPct: 3, B8_barrier: "Không thể thấy, nghe, hay cảm nhận Chúa trực tiếp", B9_openness: 4, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?", "Tại sao có quá nhiều tôn giáo — cái nào đúng?", "Tại sao người theo đạo vẫn sống giả hình, phán xét người khác?", "Vũ trụ hình thành từ đâu — khoa học hay Đức Chúa Trời?"] },
  { year: "Năm 3", school: "UTE", gender: "Nam", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 4, B3_needBigger: 3, B5_priority: 3, B6_view: "Có thể có một Đấng Tạo Hóa, nhưng tôi chưa rõ", B7_beliefPct: 3, B8_barrier: "Khoa học đã giải thích được hầu hết mọi thứ", B9_openness: 4, B10_questions: ["Có một chân lý tuyệt đối không, hay mọi thứ đều tương đối?"] },
  { year: "Năm 3", school: "HCMUE", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 4, B3_needBigger: 4, B5_priority: 7, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 3, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 4, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?", "Khoa học và đức tin có thể cùng tồn tại không?", "Có một chân lý tuyệt đối không, hay mọi thứ đều tương đối?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?"] },
  { year: "Năm 3", school: "VYA", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Có bình an nội tâm — biết mình là ai và mình thuộc về đâu", B2_emptiness: 3, B3_needBigger: 4, B5_priority: 5, B6_view: "Tôi khá chắc là không có Chúa / thần linh", B7_beliefPct: 4, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 2, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?", "Vũ trụ hình thành từ đâu — khoa học hay Đức Chúa Trời?"] },
  { year: "Năm 1", school: "HUIT", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 3, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 3, B3_needBigger: 5, B5_priority: 1, B6_view: "Tôi khá chắc là không có Chúa / thần linh", B7_beliefPct: 1, B8_barrier: "Đau khổ và bất công trên thế giới quá nhiều", B9_openness: 1, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?"] },
  { year: "Năm 3", school: "IUH", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 4, B3_needBigger: 4, B5_priority: 4, B6_view: "Tôi không biết và không chắc (bất khả tri)", B7_beliefPct: 3, B8_barrier: "Khoa học đã giải thích được hầu hết mọi thứ", B9_openness: 4, B10_questions: ["Có một chân lý tuyệt đối không, hay mọi thứ đều tương đối?", "Tôi sống tốt đã đủ chưa, cần gì đến Chúa hay đức tin?"] },
  { year: "Năm 1", school: "ULAW", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 4, B3_needBigger: 4, B5_priority: 9, B6_view: "Có thể có một Đấng Tạo Hóa, nhưng tôi chưa rõ", B7_beliefPct: 1, B8_barrier: "Tôn giáo bị lợi dụng để kiếm tiền / quyền lực", B9_openness: 1, B10_questions: ["Tại sao có quá nhiều tôn giáo — cái nào đúng?", "Tại sao người theo đạo vẫn sống giả hình, phán xét người khác?", "Vũ trụ hình thành từ đâu — khoa học hay Đức Chúa Trời?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?"] },
  { year: "Năm 1", school: "UFM", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 5, B3_needBigger: 4, B5_priority: 8, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 1, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 2, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?", "Có một chân lý tuyệt đối không, hay mọi thứ đều tương đối?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?", "Tôi là ai và mình đang sống vì điều gì?"] },
  { year: "Năm 1", school: "VLU", gender: "Nữ", religion: "Thiên Chúa giáo (Công giáo)", B1_pressure: 5, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 5, B3_needBigger: 5, B5_priority: 5, B6_view: "Tôi tin là có Đức Chúa Trời", B7_beliefPct: 8, B8_barrier: "Không thể thấy, nghe, hay cảm nhận Chúa trực tiếp", B9_openness: 4, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?", "Nếu Chúa thật, tại sao Ngài im lặng trước đau khổ của tôi?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?", "Tôi là ai và mình đang sống vì điều gì?"] },
  { year: "Năm 1", school: "ULAW", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 2, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 1, B3_needBigger: 2, B5_priority: 2, B6_view: "Tôi đang tìm hiểu và cởi mở", B7_beliefPct: 2, B8_barrier: "Đau khổ và bất công trên thế giới quá nhiều", B9_openness: 1, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?"] },
  { year: "Năm 3", school: "UTH", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 4, B3_needBigger: 3, B5_priority: 4, B6_view: "Tôi từng tin nhưng đã không còn tin nữa", B7_beliefPct: 5, B8_barrier: "Người có đạo sống không khác người không có đạo", B9_openness: 1, B10_questions: ["Nếu Chúa tốt lành và toàn năng, tại sao có quá nhiều đau khổ?"] },
  { year: "Năm 1", school: "ULAW", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 3, B4_success: "Có bình an nội tâm — biết mình là ai và mình thuộc về đâu", B2_emptiness: 4, B3_needBigger: 5, B5_priority: 7, B6_view: "Tôi đang tìm hiểu và cởi mở", B7_beliefPct: 8, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 3, B10_questions: ["Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?", "Tôi là ai và mình đang sống vì điều gì?"] },
  { year: "Năm 1", school: "VLU", gender: "Nữ", religion: "Phật giáo / Thờ cúng tổ tiên", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 3, B3_needBigger: 2, B5_priority: 4, B6_view: "Có thể có một Đấng Tạo Hóa, nhưng tôi chưa rõ", B7_beliefPct: 5, B8_barrier: "Tôn giáo bị lợi dụng để kiếm tiền / quyền lực", B9_openness: 3, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?", "Khoa học và đức tin có thể cùng tồn tại không?", "Có một chân lý tuyệt đối không, hay mọi thứ đều tương đối?", "Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 2", school: "HCMUT", gender: "Nữ", religion: "Không theo tôn giáo nào", B1_pressure: 2, B4_success: "Sống có ích cho người khác và xã hội", B2_emptiness: 2, B3_needBigger: 3, B5_priority: 3, B6_view: "Tôi khá chắc là không có Chúa / thần linh", B7_beliefPct: 2, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 3, B10_questions: ["Khoa học và đức tin có thể cùng tồn tại không?", "Tôi sống tốt đã đủ chưa, cần gì đến Chúa hay đức tin?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?", "Tôi là ai và mình đang sống vì điều gì?"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nữ", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 5, B3_needBigger: 3, B5_priority: 4, B6_view: "Tôi không quan tâm đến chủ đề này", B7_beliefPct: 1, B8_barrier: "Chưa bao giờ thật sự tìm hiểu nên không rõ", B9_openness: 2, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 2, B4_success: "Có bình an nội tâm — biết mình là ai và mình thuộc về đâu", B2_emptiness: 1, B3_needBigger: 1, B5_priority: 10, B6_view: "Tôi tin là có Đức Chúa Trời", B7_beliefPct: 10, B8_barrier: "Không thể thấy, nghe, hay cảm nhận Chúa trực tiếp", B9_openness: 3, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 2, B4_success: "Có gia đình hạnh phúc và các mối quan hệ sâu sắc", B2_emptiness: 3, B3_needBigger: 3, B5_priority: 5, B6_view: "Tôi đang tìm hiểu và cởi mở", B7_beliefPct: 1, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 3, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nữ", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 1, B3_needBigger: 4, B5_priority: 8, B6_view: "Tôi khá chắc là không có Chúa / thần linh", B7_beliefPct: 1, B8_barrier: "Thiếu bằng chứng cụ thể, có thể kiểm chứng", B9_openness: 1, B10_questions: ["Sau khi chết, chúng ta sẽ đi về đâu?", "Khoa học và đức tin có thể cùng tồn tại không?", "Tại sao người theo đạo vẫn sống giả hình, phán xét người khác?", "Có điều gì ý nghĩa hơn thành tích, tiền bạc và danh tiếng không?"] },
  { year: "Năm 3", school: "HCMUT", gender: "Nam", religion: "Không theo tôn giáo nào", B1_pressure: 4, B4_success: "Đạt được sự độc lập tài chính và ổn định", B2_emptiness: 4, B3_needBigger: 4, B5_priority: 9, B6_view: "Không quan tâm", B7_beliefPct: 1, B8_barrier: "Không quan tâm", B9_openness: 1, B10_questions: ["Tôi không có câu hỏi nào như vậy"] },
]

export const TOTAL = responses.length
